pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo/' }
    }
}

rootProject.name = 'DocumentSkewCorrection'
include ':app'
include ':documentskewcorrection-core'
include ':documentskewcorrection-opencv'
include ':documentskewcorrection-tensorflow'
include ':documentskewcorrection-hms'
include ':documentskewcorrection-ui'
