plugins {
    id 'com.android.library'
}

android {
    namespace 'io.github.alexmofer.documentskewcorrection.core'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        minSdk 26
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }

        multipleVariants {
            withSourcesJar()
            withJavadocJar()
            allVariants()
        }
    }
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.9.1'
    compileOnly 'androidx.exifinterface:exifinterface:1.4.2'
}

//apply from: "maven-central-aar.gradle"
//apply from: "maven-local-aar.gradle"