plugins {
    id 'com.android.library'
}

android {
    namespace 'io.github.alexmofer.documentskewcorrection.core'
    compileSdkVersion 36
    ndkVersion '28.2.13676358'
    buildToolsVersion '36.0.0'

    defaultConfig {
        minSdkVersion 24
        consumerProguardFiles 'consumer-rules.pro'
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11 -frtti -fexceptions'
                arguments '-DANDROID_STL=c++_shared', '-DOpenCV_DIR=OpenCV-android-sdk/sdk/native/jni'
                abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
            version '4.0.2'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }

        multipleVariants {
            withSourcesJar()
            withJavadocJar()
            allVariants()
        }
    }
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.9.1'
    compileOnly 'androidx.exifinterface:exifinterface:1.4.1'
}

//apply from: "maven-central-aar.gradle"
//apply from: "maven-local-aar.gradle"